# CONFIGURANDO O NOME DA API    
server:
  servlet:
    context-path: /prodfocus 
    
# CONFIGURANDO O DATABASE    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prodfocus?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Alisson71011
  jpa:
    hibernate:
      ddl-auto: update
      
# CONFIGURANDO O SWAGGER    
springdoc:
  swagger-ui:
    path: /swagger